// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_estamos_bien_en_el_refugio_los_33 = "CgkIzIuQypIeEAIQGg"; // <GPGSID>
        public const string leaderboard_world_class_player_online = "CgkIzIuQypIeEAIQHA"; // <GPGSID>
        public const string achievement_5_minutes = "CgkIzIuQypIeEAIQKw"; // <GPGSID>
        public const string achievement_please_stop = "CgkIzIuQypIeEAIQFA"; // <GPGSID>
        public const string achievement_welcome_to_hell = "CgkIzIuQypIeEAIQBQ"; // <GPGSID>
        public const string achievement_double_kill = "CgkIzIuQypIeEAIQHw"; // <GPGSID>
        public const string achievement_wisdom = "CgkIzIuQypIeEAIQCw"; // <GPGSID>
        public const string leaderboard_time_master = "CgkIzIuQypIeEAIQJQ"; // <GPGSID>
        public const string achievement_2_minutes = "CgkIzIuQypIeEAIQKg"; // <GPGSID>
        public const string achievement_rockrock = "CgkIzIuQypIeEAIQCA"; // <GPGSID>
        public const string achievement_10_minutes = "CgkIzIuQypIeEAIQLA"; // <GPGSID>
        public const string achievement_1_minute = "CgkIzIuQypIeEAIQKQ"; // <GPGSID>
        public const string leaderboard_knockouts_online = "CgkIzIuQypIeEAIQHQ"; // <GPGSID>
        public const string leaderboard_floor_master = "CgkIzIuQypIeEAIQAQ"; // <GPGSID>
        public const string achievement_first_ko = "CgkIzIuQypIeEAIQHg"; // <GPGSID>
        public const string achievement_im_proud = "CgkIzIuQypIeEAIQCg"; // <GPGSID>
        public const string achievement_floor_10 = "CgkIzIuQypIeEAIQDg"; // <GPGSID>
        public const string achievement_todo_calza = "CgkIzIuQypIeEAIQEQ"; // <GPGSID>
        public const string achievement_floor_30 = "CgkIzIuQypIeEAIQEA"; // <GPGSID>
        public const string achievement_floor_20 = "CgkIzIuQypIeEAIQDw"; // <GPGSID>
        public const string achievement_floor_50 = "CgkIzIuQypIeEAIQEw"; // <GPGSID>
        public const string achievement_floor_40 = "CgkIzIuQypIeEAIQEg"; // <GPGSID>
        public const string achievement_bigboy = "CgkIzIuQypIeEAIQCQ"; // <GPGSID>
        public const string achievement__jan_jan_ken_up = "CgkIzIuQypIeEAIQDQ"; // <GPGSID>
        public const string achievement_combo_x_30 = "CgkIzIuQypIeEAIQGA"; // <GPGSID>
        public const string achievement_combo_x_20 = "CgkIzIuQypIeEAIQFw"; // <GPGSID>
        public const string achievement_combo_x_10 = "CgkIzIuQypIeEAIQFg"; // <GPGSID>
        public const string achievement_combo_x_50 = "CgkIzIuQypIeEAIQGw"; // <GPGSID>
        public const string achievement_combo_x_40 = "CgkIzIuQypIeEAIQGQ"; // <GPGSID>
        public const string achievement_triple_kill = "CgkIzIuQypIeEAIQIA"; // <GPGSID>
        public const string achievement_god_level = "CgkIzIuQypIeEAIQFQ"; // <GPGSID>
        public const string leaderboard_intraterrestrial = "CgkIzIuQypIeEAIQAw"; // <GPGSID>
        public const string achievement_deluxe = "CgkIzIuQypIeEAIQIw"; // <GPGSID>
        public const string achievement_30_seconds = "CgkIzIuQypIeEAIQKA"; // <GPGSID>
        public const string achievement_school_time = "CgkIzIuQypIeEAIQBg"; // <GPGSID>
        public const string achievement_10_seconds = "CgkIzIuQypIeEAIQJw"; // <GPGSID>
        public const string achievement_sweetheart = "CgkIzIuQypIeEAIQDA"; // <GPGSID>
        public const string leaderboard_knockouts_offline = "CgkIzIuQypIeEAIQJg"; // <GPGSID>
        public const string achievement_illuminati = "CgkIzIuQypIeEAIQBw"; // <GPGSID>
        public const string leaderboard_score_breaker = "CgkIzIuQypIeEAIQAg"; // <GPGSID>
        public const string achievement_penta_kill = "CgkIzIuQypIeEAIQIg"; // <GPGSID>
        public const string leaderboard_combo_master = "CgkIzIuQypIeEAIQBA"; // <GPGSID>
        public const string achievement_quadra_kill = "CgkIzIuQypIeEAIQIQ"; // <GPGSID>

}

